server:
  port: 3001
  basePath: ''
application:
  domain: lowes-hw-sh.op
  name: 'Hardware Shop'
  logo:  lowes_logo.png
  favicon: 
  theme:  blue-lightblue # Options: bluegrey-lightgreen blue-lightblue deeppurple-amber indigo-pink pink-bluegrey purple-green deeporange-indigo
  showVersionNumber: true
  showGitHubLinks: true
  localBackupEnabled: true
  numberOfRandomFakeUsers: 0
  altcoinName: Juicycoin
  privacyContactEmail: donotreply@owasp-juice.shop
  customMetricsPrefix: juiceshop
  chatBot:
    name: 'Lowes-Bot'
    greeting: "Nice to meet you <customer-name>, I'm <bot-name>"
    trainingData: 'botDefaultTrainingData.json'
    defaultResponse: "Sorry I couldn't understand what you were trying to say"
    avatar: 'JuicyChatBot.png'
  social:
    twitterUrl: 'https://twitter.com/owasp_juiceshop'
    facebookUrl: 'https://www.facebook.com/owasp.juiceshop'
    slackUrl: 'https://owasp.org/slack/invite'
    redditUrl: 'https://www.reddit.com/r/owasp_juiceshop'
    pressKitUrl: 'https://github.com/OWASP/owasp-swag/tree/master/projects/juice-shop'
    questionnaireUrl: ~
  recyclePage:
    topProductImage: fruit_press.jpg
    bottomProductImage: apple_pressings.jpg
  welcomeBanner:
    showOnFirstStart: true
    title: 'Welcome to LOWES Hardware Shop!'
    message: "<p>Welcome to the Hardware Shop. Here you will find a serious of security vulnerabilities that have been customized to emulate an online shopping platform. We hope you enjoy. All credit for the orginal project goes to OWASP: </p><h1><a href='https://owasp-juice.shop' target='_blank'>https://owasp-juice.shop</a></h1>"
  cookieConsent:
    backgroundColor: '#0041C2'
    textColor: '#ffffff'
    buttonColor: '#558b2f'
    buttonTextColor: '#ffffff'
    message: 'This website uses fruit cookies to ensure you get the juiciest tracking experience.'
    dismissText: 'Me want it!'
    linkText: 'But me wait!'
    linkUrl: 'https://www.youtube.com/watch?v=9PnbKL3wuH4'
  securityTxt:
    contact: 'mailto:donotreply@owasp-juice.shop'
    encryption: 'https://keybase.io/bkimminich/pgp_keys.asc?fingerprint=19c01cb7157e4645e9e2c863062a85a8cbfbdcda'
    acknowledgements: '/#/score-board'
  promotion:
    video: owasp_promo.mp4
    subtitles: owasp_promo.vtt
  easterEggPlanet:
    name: Orangeuze
    overlayMap: orangemap2k.jpg
  googleOauth:
    clientId: '1005568560502-6hm16lef8oh46hr2d98vf2ohlnj4nfhq.apps.googleusercontent.com'
    authorizedRedirects:
      - { uri: 'https://demo.owasp-juice.shop' }
      - { uri: 'https://juice-shop.herokuapp.com' }
      - { uri: 'https://preview.owasp-juice.shop' }
      - { uri: 'https://juice-shop-staging.herokuapp.com' }
      - { uri: 'https://juice-shop.wtf' }
      - { uri: 'http://localhost:3000', proxy: 'https://local3000.owasp-juice.shop' }
      - { uri: 'http://127.0.0.1:3000', proxy: 'https://local3000.owasp-juice.shop' }
      - { uri: 'http://localhost:4200', proxy: 'https://local4200.owasp-juice.shop' }
      - { uri: 'http://127.0.0.1:4200', proxy: 'https://local4200.owasp-juice.shop' }
      - { uri: 'http://192.168.99.100:3000', proxy: 'https://localmac.owasp-juice.shop' }
      - { uri: 'http://192.168.99.100:4200', proxy: 'https://localmac.owasp-juice.shop' }
      - { uri: 'http://penguin.termina.linux.test:3000', proxy: 'https://localchromeos.owasp-juice.shop' }
      - { uri: 'http://penguin.termina.linux.test:4200', proxy: 'https://localchromeos.owasp-juice.shop' }
challenges:
  showSolvedNotifications: true
  showHints: true
  showMitigations: true
  codingChallengesEnabled: solved # Options: never  solved  always
  restrictToTutorialsFirst: false
  overwriteUrlForProductTamperingChallenge: 'https://owasp.slack.com'
  xssBonusPayload: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/771984076&color=%23ff5500&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
  safetyOverride: false
  showFeedbackButtons: true
hackingInstructor:
  isEnabled: true
  avatarImage: JuicyBot_MedicalMask.png
  hintPlaybackSpeed: normal # Options: faster fast normal slow slower
products:
  -
    name: 'Fire Extinguisher'
    price: 5.00
    deluxePrice: 3.00
    limitPerUser: 5
    description: 'Keep you and your family safe through the fire and flames'
    image: apple_juice.jpg
    reviews:
      - { text: 'Its great!', author: admin }
  -
    name: 'Head Lamp'
    description: 'This product will illuminate your life like no other!'
    price: 10.99
    deluxePrice: 8.49
    image: orange_juice.jpg
    reviews:
      - { text: 'y0ur f1r3wall needs m0r3 musc13', author: uvogin }
  -
    name: 'Plier and wire cutter'
    description: 'Easily cut wires for all your electical projects'
    price: 8.99
    image: eggfruit_juice.jpg
    reviews:
      - { text: 'I bought it, would buy again. 5/7', author: admin }
  -
    name: 'Measuring Tape'
    description: ''
    price: 4.99
    image: raspberry_juice.jpg
  -
    name: 'craftsman garage cabinet'
    description: 'Holds all your tools for all your projects!'
    price: 30.00
    deluxePrice: 35.00
    limitPerUser: 5
    image: lemon_juice.jpg
  -
    name: 'Lumber'
    description: 'Our high-quality lumber is sourced from the Himalayas'
    price: 10
    image: banana_juice.jpg
    reviews:
      - { text: 'Was great for my home project. We used this wood for a flooring project!', author: bender }
  -
    name: 'safety-weather-radios'
    description: 'These radios are a great choice for local communication'
    price: 20.10
    limitPerUser: 5
    image: fan_shirt.jpg
  -
    name: 'Pliers'
    description: 'The perfect tool for the job!'
    price: 15.99
    image: fan_girlie.jpg
  -
    name: 'Bobblehead'
    description: 'The Marvin Ellison exclusive bobblehead makes the perfect desk ornament!'
    price: 10.00
    image: marvin-bobblehead.jpg
    urlForProductTamperingChallenge: 'https://www.owasp.org/index.php/O-Saft'
  -
    name: 'Christmas Super-Surprise-Box (2014 Edition)'
    description: 'Contains a random selection of 10 bottles (each 500ml) of our tastiest juices and an extra fan shirt for an unbeatable price!'
    price: 29.99
    image: undefined.jpg
    useForChristmasSpecialChallenge: true
  -
    name: 'Rippertuer Special Juice'
    description: 'Contains a magical collection of the rarest fruits gathered from all around the world, like Cherymoya Annona cherimola, Jabuticaba Myrciaria cauliflora, Bael Aegle marmelos... and others, at an unbelievable price! <br/><span style="color:red;">This item has been made unavailable because of lack of safety standards.</span>'
    price: 16.99
    image: undefined.jpg
    keywordsForPastebinDataLeakChallenge:
      - hueteroneel
      - eurogium edule
  -
    name: 'Electric dryer'
    description: 'This dryer will dry all of your items quickyl and energy efficiently!'
    price: 999.99
    image: sticker.png
    deletedDate: '2017-04-28'
  -
    name: 'Pliers'
    description: 'Upgrade your clothes with washer safe <a href="https://www.stickeryou.com/products/owasp-juice-shop/794" target="_blank">iron-ons</a> of the OWASP Juice Shop or CTF Extension logo!'
    price: 14.99
    image: iron-on.jpg
  -
    name: 'Kobalt Combo Kit'
    description: 'This Kobalt combo kit is the perfect companion for the job site.'
    price: 15.99
    image: magnets.jpg
  -
    name: 'Refrigerator'
    description: 'This fridge is the perfect size for any home, with ice dispensing technology!'
    price: 899.98
    image: sticker_page.jpg
  -
    name: 'Screwdriver'
    description: 'This high-quality screwdriver is made from titanium for any tough job'
    price: 4.99
    image: sticker_single.jpg
  -
    name: 'mower trimmer brush cutter attachment'
    description: 'Check out this handy attachment for all your gardening needs!'
    price: 14.99
    image: tattoo.jpg
    reviews:
      - { text: 'I straight-up gots nuff props fo this tool brooo', author: rapper }
  -
    name: 'Safety Tape'
    description: 'Stay highly visible with this lovely safety tape!'
    price: 5.00
    image: fan_mug.jpg
  -
    name: 'Safety Harness'
    description: 'Stay safe, stay awesome with this safety harness guaranteed to handle loads in excess of 2 lbs'
    price: 49.99
    image: fan_hoodie.jpg
  -
    name: 'OWASP Juice Shop-CTF Velcro Patch'
    description: '4x3.5" embroidered patch with velcro backside. The ultimate decal for every tactical bag or backpack!'
    price: 2.92
    quantity: 5
    limitPerUser: 5
    image: velcro-patch.jpg
    reviews:
      - { text: 'This thang would look phat on Bobby''s jacked fur coat!', author: rapper }
      - { text: 'Looks so much better on my uniform than the boring Starfleet symbol.', author: jim }
  -
    name: 'Work Gloves'
    description: 'Protect yoour hands from all the dirt and grime using these responsibly sourced work gloves!'
    price: 6.99
    image: woodruff_syrup.jpg
  -
    name: 'Electric Fireplace'
    description: 'Coz up with the electric fireplace!'
    price: 799.99
    image: green_smoothie.jpg
    reviews:
      - { text: 'Amazing! Kept my house nice and cozy all winter long!', author: jim }
  -
    name: 'Quince Juice (1000ml)'
    description: 'Juice of the <em>Cydonia oblonga</em> fruit. Not exactly sweet but rich in Vitamin C.'
    price: 4.99
    image: quince.jpg
  -
    name: 'Bosch Multitool Kit'
    description: 'The Bosch Multitool is the perfect compainion for any of your projects large or small'
    price: 8.00
    limitPerUser: 5
    image: apple_pressings.jpg
  -
    name: 'Knee Pads'
    description: 'Keep your knees safe with these patent pending kneepads!'
    price: 89.99
    image: fruit_press.jpg
    reviews:
      - { text: 'dese things worked so good when I was working on my house!', author: rapper }
  -
    name: 'OWASP Juice Shop Logo (3D-printed)'
    description: 'This rare item was designed and handcrafted in Sweden. This is why it is so incredibly expensive despite its complete lack of purpose.'
    price: 99.99
    image: 3d_keychain.jpg # Exif metadata contains "OpenSCAD" as subtle hint...
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type
    exifForBlueprintChallenge:
      - OpenSCAD
  -
    name: 'Brushless Cordless Hammer Drill Driver'
    description: 'Master all the projects with the classic cordless drill!'
    price: 278.74
    quantity: 0
    image: artwork.jpg
    deletedDate: '2020-12-24'
  -
    name: 'Global OWASP WASPY Award 2017 Nomination'
    description: 'Your chance to nominate up to three quiet pillars of the OWASP community ends 2017-06-30! <a href="https://www.owasp.org/index.php/WASPY_Awards_2017">Nominate now!</a>'
    price: 0.03
    image: waspy.png
    deletedDate: '2017-07-01'
  -
    name: 'Strawberry Juice (500ml)'
    description: 'Sweet & tasty!'
    price: 3.99
    image: strawberry_juice.jpeg
  -
    name: 'Wrench'
    description: 'Handle all the projects with this amazing Wrench!'
    price: 2.99
    image: carrot_juice.jpeg
    reviews:
      - { text: '0 st4rs f0r 7h3 h0rr1bl3 s3cur17y', author: uvogin }
  -
    name: 'Microwave'
    description: 'Zap your food until it can't be zapped no more. This microwave is rated for 8000 amps, enough to cook a wildebeast!'
    price: 60.00
    image: stickersheet_se.png
    deletedDate: '2017-09-20'
  -
    name: 'Hammer'
    description: 'This hammer is ready to hammer away the competition with its titanium construction and durable grip'
    price: 5.99
    image: cover_small.jpg
    reviews:
      - { text: 'Even more interesting than watching Interdimensional Cable!', author: morty }
  -
    name: 'Melon Bike (Comeback-Product 2018 Edition)'
    description: 'The wheels of this bicycle are made from real water melons. You might not want to ride it up/down the curb too hard.'
    price: 2999
    quantity: 3
    limitPerUser: 1
    image: melon_bike.jpeg
  -
    name: 'OWASP Juice Shop Coaster (10pcs)'
    description: 'Our 95mm circle coasters are printed in full color and made from thick, premium coaster board.'
    price: 19.99
    quantity: 0
    image: coaster.jpg
  -
    name: 'OWASP Snakes and Ladders - Web Applications'
    description: 'This amazing web application security awareness board game is <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=1969196030">available for Tabletop Simulator on Steam Workshop</a> now!'
    price: 0.01
    quantity: 8
    image: snakes_ladders.jpg
    reviews:
      - { text: 'Wait for a 10$ Steam sale of Tabletop Simulator!', author: bjoernOwasp }
  -
    name: 'craftsman tool set'
    description: 'The craftsmen toolkit is the perfect solution to handle all your projects.'
    price: 800.00
    quantity: 0
    image: snakes_ladders_m.jpg
    reviews:
      - { text: "Wow! Amazing product", author: jim }
  -
    name: 'Hard Hats'
    description: "this hard hat will keep you conscious in case of any head related trauma!"
    price: 20.00
    quantity: 0
    image: holo_sticker.png
    reviews:
      - { text: "Rad, dude!", author: rapper }
      - { text: "Looks great on Bones' new noggin!", author: jim }
      - { text: "I need this to keep my head protected!", author: bender }
  -
    name: 'Drill Bits'
    description: "These drill bits are sure to handle any materials you need to drill a hole into!"
    price: 13.49
    quantity: 0
    limitPerUser: 1
    image: fan_facemask.jpg
    reviews:
      - { text: "K33p5 y0ur ju1cy 5plu773r 70 y0ur53lf!", author: uvogin }
      - { text: "These drill bits broke 19 times when I tried to use them for my project :(", author: bender }
  -
    name: 'Juice Shop Adversary Trading Card (Common)'
    description: 'Common rarity "Juice Shop" card for the <a href="https://docs.google.com/forms/d/e/1FAIpQLSecLEakawSQ56lBe2JOSbFwFYrKDCIN7Yd3iHFdQc5z8ApwdQ/viewform">Adversary Trading Cards</a> CCG.'
    price: 2.99
    deluxePrice: 0.99
    deletedDate: '2020-11-30'
    limitPerUser: 5
    image: ccg_common.png
    reviews:
      - { text: "Ooooh, puny human playing Mau Mau, now?", author: bender }
  -
    name: 'Juice Shop Adversary Trading Card (Super Rare)'
    description: 'Super rare "Juice Shop" card with holographic foil-coating for the <a href="https://docs.google.com/forms/d/e/1FAIpQLSecLEakawSQ56lBe2JOSbFwFYrKDCIN7Yd3iHFdQc5z8ApwdQ/viewform">Adversary Trading Cards</a> CCG.'
    price: 99.99
    deluxePrice: 69.99
    deletedDate: '2020-11-30'
    quantity: 2
    limitPerUser: 1
    image: ccg_foil.png
    reviews:
      - { text: "Mau Mau with bling-bling? Humans are so pathetic!", author: bender }
  -
    name: 'Weed Cutter Grass whip'
    description: 'Trim the grass and more with this amazing tool!'
    price: 300.00
    quantity: 1
    limitPerUser: 1
    image: permafrost.jpg
    reviews:
      - { text: "üßä Let it go, let it go üé∂ Can't hold it back anymore üé∂ Let it go, let it go üé∂ Turn away and slam the door ‚ùÑÔ∏è", author: rapper }
  -
    name: 'Welding Torch Kit'
    description: 'Weld metal, weld wood, weld the world back together with this incredible kit!'
    price: 100.00
    quantity: 1
    image: artwork2.jpg
    reviews:
      - { text: "I'd stand on my head to make you a deal for this.", author: stan }
      - { text: "Just when my opinion of humans couldn't get any lower, along comes Stan...", author: bender }
  -
    name: 'OWASP Juice Shop Card (non-foil)'
    description: 'Mythic rare <small><em>(obviously...)</em></small> card "OWASP Juice Shop" with three distinctly useful abilities. Alpha printing, mint condition. A true collectors piece to own!'
    price: 1000
    quantity: 3
    limitPerUser: 1
    image: card_alpha.jpg
    reviews:
      - { text: 'DO NOT PLAY WITH THIS! Double-sleeve, then put it in the GitHub Arctic Vault for perfect preservation and boost of secondary market value!', author: accountant }
  -
    name: '20th Anniversary Celebration Ticket'
    description: 'Get your <a href="https://20thanniversary.owasp.org/" target="_blank">free üé´ for OWASP 20th Anniversary Celebration</a> online conference! Hear from world renowned keynotes and special speakers, network with your peers and interact with our event sponsors. With an anticipated 10k+ attendees from around the world, you will not want to miss this live on-line event!'
    price: 0.00000000000000000001
    deletedDate: '2021-09-25'
    limitPerUser: 1
    image: 20th.jpeg
    reviews:
      - { text: "I'll be there! Will you, too?", author: bjoernOwasp }
memories:
  -
    image: 'magn(et)ificent!-1571814229653.jpg'
    caption: 'Magn(et)ificent!'
    user: bjoernGoogle
  -
    image: 'my-rare-collectors-item!-[Ã≤ÃÖ$Ã≤ÃÖ(Ã≤ÃÖ-Õ°¬∞-Õú ñ-Õ°¬∞Ã≤ÃÖ)Ã≤ÃÖ$Ã≤ÃÖ]-1572603645543.jpg'
    caption: 'My rare collectors item! [Ã≤ÃÖ$Ã≤ÃÖ(Ã≤ÃÖ Õ°¬∞ Õú ñ Õ°¬∞Ã≤ÃÖ)Ã≤ÃÖ$Ã≤ÃÖ]'
    user: bjoernGoogle
  -
    image: 'favorite-hiking-place.png'
    caption: 'I love going hiking here...'
    geoStalkingMetaSecurityQuestion: 14
    geoStalkingMetaSecurityAnswer: 'Daniel Boone National Forest'
  -
    image: 'IMG_4253.jpg'
    caption: 'My old workplace...'
    geoStalkingVisualSecurityQuestion: 10
    geoStalkingVisualSecurityAnswer: 'ITsec'
ctf:
  showFlagsInNotifications: false
  showCountryDetailsInNotifications: none # Options: none  name  flag  both
  countryMapping: ~
